### PR TITLE
NOT READY TO MERGE: Access separate SPARQL endpoints

### PR DESCRIPTION
**Pull request by StevenMaude**
Use different credentials for public and private SPARQL endpoints.

Needs:

- [x] README updating
- [x] Separate public and private API keys too and enabling endpoint access according to whether they're public/private.

### CODE REVIEW

**Comment by StevenMaude** [comment]
Closing because GitHub won't let you switch target branch of a pull request. Will make a new one.

**Comment by pwaller** [comment]
For the record, rather than using the heading for state, I have found that assignments work quite well to assert intent. If it's unassigned, you can ask if you can take it. If it's assigned to the user who made the PR, they wish to continue development on it.

As usual, good judgment should be exercised.

If something is critical and you do want to stamp the PR to avoid doubt, a message in the body with heading text is fine.

**Comment by StevenMaude** [comment]
In this case, we wanted to be careful about merging as it could potentially expose LexisNexis data that was only sanctioned for project member use.

**Comment by pwaller** [comment]
No worries! I hope I didn't come across as chewing you out. I'm sure you were doing a reasonable thing.

**Comment by StevenMaude** [comment]
Not at all. I'm always welcoming of suggestions for doing things better.

**Pull request closed without merging**
